// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Initialize(arg1) {
  return window['go']['helpers']['Service']['Initialize'](arg1);
}

export function SelectFile() {
  return window['go']['helpers']['Service']['SelectFile']();
}
