// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Initialize(arg1) {
  return window['go']['languages']['Service']['Initialize'](arg1);
}

export function RunAllParticipants(arg1, arg2, arg3) {
  return window['go']['languages']['Service']['RunAllParticipants'](arg1, arg2, arg3);
}
