// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateTests(arg1, arg2) {
  return window['go']['languages']['Service']['GenerateTests'](arg1, arg2);
}

export function Initialize(arg1) {
  return window['go']['languages']['Service']['Initialize'](arg1);
}

export function RunAllParticipants(arg1, arg2, arg3, arg4) {
  return window['go']['languages']['Service']['RunAllParticipants'](arg1, arg2, arg3, arg4);
}
