// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddOneParticipant(arg1:models.Participant,arg2:string):Promise<void>;

export function GetParticipants():Promise<Array<models.Participant>>;

export function Initialize(arg1:context.Context):Promise<void>;
