// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOneParticipant(arg1, arg2) {
  return window['go']['models']['ParticipantService']['AddOneParticipant'](arg1, arg2);
}

export function GetParticipants() {
  return window['go']['models']['ParticipantService']['GetParticipants']();
}

export function Initialize(arg1) {
  return window['go']['models']['ParticipantService']['Initialize'](arg1);
}
