// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddSubmission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetProblems():Promise<Array<models.Problem>>;

export function Initialize(arg1:context.Context):Promise<void>;

export function WriteProblem(arg1:models.Problem):Promise<void>;
