// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubmission(arg1, arg2, arg3) {
  return window['go']['models']['ProblemService']['AddSubmission'](arg1, arg2, arg3);
}

export function GetProblems() {
  return window['go']['models']['ProblemService']['GetProblems']();
}

export function Initialize(arg1) {
  return window['go']['models']['ProblemService']['Initialize'](arg1);
}

export function WriteProblem(arg1) {
  return window['go']['models']['ProblemService']['WriteProblem'](arg1);
}
