// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOneParticipant(arg1, arg2) {
  return window['go']['models']['Service']['AddOneParticipant'](arg1, arg2);
}

export function AddSubmission(arg1, arg2, arg3) {
  return window['go']['models']['Service']['AddSubmission'](arg1, arg2, arg3);
}

export function GetParticipants() {
  return window['go']['models']['Service']['GetParticipants']();
}

export function GetProblems() {
  return window['go']['models']['Service']['GetProblems']();
}

export function Initialize(arg1) {
  return window['go']['models']['Service']['Initialize'](arg1);
}

export function WriteProblem(arg1) {
  return window['go']['models']['Service']['WriteProblem'](arg1);
}
