// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddOneParticipant(arg1:models.Participant,arg2:string):Promise<void>;

export function AddSubmission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetGeneratorScript(arg1:string):Promise<string>;

export function GetParticipants(arg1:string):Promise<Array<models.Participant>>;

export function GetProblems():Promise<Array<models.Problem>>;

export function GetSolveResults(arg1:string):Promise<Array<models.ParticipantSolveResult>>;

export function GetTestCases(arg1:string):Promise<Array<models.TestCase>>;

export function Initialize(arg1:context.Context):Promise<void>;

export function WriteGeneratorScript(arg1:string,arg2:string):Promise<void>;

export function WriteProblem(arg1:models.Problem):Promise<void>;

export function WriteSolution(arg1:string,arg2:string):Promise<void>;
