// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOneParticipant(arg1, arg2) {
  return window['go']['models']['Service']['AddOneParticipant'](arg1, arg2);
}

export function AddSubmission(arg1, arg2, arg3) {
  return window['go']['models']['Service']['AddSubmission'](arg1, arg2, arg3);
}

export function DeleteProblem(arg1) {
  return window['go']['models']['Service']['DeleteProblem'](arg1);
}

export function GetGeneratorScript(arg1) {
  return window['go']['models']['Service']['GetGeneratorScript'](arg1);
}

export function GetParticipants(arg1) {
  return window['go']['models']['Service']['GetParticipants'](arg1);
}

export function GetProblems() {
  return window['go']['models']['Service']['GetProblems']();
}

export function GetSolveResults(arg1) {
  return window['go']['models']['Service']['GetSolveResults'](arg1);
}

export function GetTestCases(arg1) {
  return window['go']['models']['Service']['GetTestCases'](arg1);
}

export function Initialize(arg1) {
  return window['go']['models']['Service']['Initialize'](arg1);
}

export function WriteGeneratorScript(arg1, arg2) {
  return window['go']['models']['Service']['WriteGeneratorScript'](arg1, arg2);
}

export function WriteProblem(arg1) {
  return window['go']['models']['Service']['WriteProblem'](arg1);
}

export function WriteSolution(arg1, arg2) {
  return window['go']['models']['Service']['WriteSolution'](arg1, arg2);
}
